<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Amql.Gguf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Amql.Safetensors\Amql.Safetensors.csproj" />
  </ItemGroup>
</Project>